{
 "title": "Mattermost bot dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{}[1m]))"
    }
   ]
  },
  {
   "title": "App Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_connect_duration_seconds_count{}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_connect_duration_seconds_count{status=~\"5..\"}[1m]))"
    }
   ]
  }
 ]
}