apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bff.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bff.fullname" . }}
type: Opaque
data:
  JSON_TOKEN_SECRET: {{ .Values.global.jwt.secret  | b64enc | quote }}

