apiVersion: v1
kind: Service
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "bff.selectorLabels" . | nindent 4 }}
