apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "constructor.fullname" . }}
  labels:
    {{- include "constructor.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "constructor.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "constructor.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    port: actuator
    path: /actuator/prometheus
