apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storage.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storage.fullname" . }}
type: Opaque
data:
  DB_HOST: {{ printf "bricklayer-postgresql"  | b64enc | quote }}
  DB_NAME: {{ .Values.global.postgresql.auth.database  | b64enc | quote }}
  MASTER_PASSWORD: {{ .Values.global.postgresql.auth.password  | b64enc | quote }}
  MASTER_USERNAME: {{ .Values.global.postgresql.auth.username  | b64enc | quote }}
  DB_PORT: {{ .Values.global.postgresql.servicePort  | b64enc | quote }}

