apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "engine.fullname" . }}
type: Opaque
data:
  MQ_USERNAME: {{ .Values.global.mq.user  | b64enc | quote }}
  MQ_PASSWORD: {{ .Values.global.mq.password  | b64enc | quote }}
