apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    metadata:
      name: migration
    annotations:
      # This is what defines this resource as a hook. Without this line, the
      # job is considered part of the release.
      "helm.sh/hook": post-install
      "helm.sh/hook-weight": "-5"
      "helm.sh/hook-delete-policy": hook-succeeded
    spec:
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bricklayer-postgresql
                  key: postgres-password
          command:
            - sh
            - "-c"
            - |
              psql postgres://pstgrs:psswrd@bricklayer-postgresql/bricklayer <<'EOF'
                create table if not exists bots (
                id serial primary key,
                user_id varchar not null,
                create_at bigint,
                update_at bigint,
                delete_at bigint,
                username varchar unique not null,
                display_name varchar not null,
                description varchar not null,
                owner_id varchar not null
                );
                create table if not exists users (
                id serial primary key,
                username varchar unique not null,
                pass varchar not null
                );
                create table if not exists roles (
                id serial primary key,
                role_name varchar unique not null,
                description varchar not null
                );
                create table if not exists user_role (
                usr_id int not null,
                role_id int not null,
                primary key (usr_id, role_id)
                );
              EOF
      restartPolicy: Never