# Default values for bricklayer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  postgresql:
    enabled: true
    auth:
      database: "bricklayer"
      password: "psswrd"
      username: "pstgrs"
    servicePort: "5432"
  jwt:
    secret: "B#PmRL5mJPF7J2EJK4X$Y|ikmegMrJ4TPNBh|{zgTPnDCWwFLTFY}4lgN?*iul{F|wUZdsc#PQ@KYX36JSNZ17r8OR7DfH7n?4G"
  mq:
    user: "bricklayer"
    password: "password"
kafka:
  enabled: true
  sasl:
    client:
      users:
        - bricklayer
      passwords:
        - password
bff:
  enabled: true
constructor:
  enabled: true
engine:
  enabled: true
storage:
  enabled: true
user:
  enabled: true
